### PR TITLE
Exception form

### PR DESCRIPTION
**Pull request by Arcfej**
At the moment, one exception form is included on the Details Report page. The reason for this is to apply Bootstrap to the form, as it's imported on the page. The javascript behaviour is also imported on the page, not on the component. The reason for this is that I use Bootstrap's javascript.

I have a concern, I'd like to have ideas for it. Right now, the IDs of elements are hardcoded on the `exception-form.html`. But the Details Report page can have multiple exception forms on it. For this, IDs have to be randomised. Any ideas for this?

### CODE REVIEW

**Comment by idrismahamdi** [comment]
I don't understand your question @Arcfej

**Review by idrismahamdi — CHANGES_REQUESTED** [review]
Dashboard.html is not finished so shouldn't be pushed to master
DetailsReport.php and index.php  is all in an echo statement??
connection.php file doesn't need to be changed

**Comment by Arcfej** [comment]
- You're right, I left some changes for the connection.php accidentally.
- php files are fixed,
- You're also right that in this form DetailsReport should not be pushed to master. This form is ideal for testing the exception form if it works. I'll remove the page from this branch and update and make the component work on its own

**Comment by Arcfej** [comment]
- I changed the index.php into a page component. It's now a template for pages.
- To be able to test the form, you have to include the html and the js file in a page like this:
`<?php include "../ExceptionForm/exception-form.html" ?>`
`<script type="module" src="../ExceptionForm/exception-form.js"></script>`

**Review by jweir211 — APPROVED** [review]

**Comment by jweir211** [comment]
I have removed dashboard.html I have a copy of it and it should still be on my branch anyway

**Review by idrismahamdi — APPROVED** [review]

**Pull request merged**
